WebWeatherApp/Models/ErrorViewModel.cs
using System;

namespace WebWeatherApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebWeatherApp/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WeatherApp.Data;

namespace WebWeatherApp.Controllers
{
    public class WeatherController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Search()
        {
            var WeatherDataList = await Seed.PopulateByRandValues();
            return View(WeatherDataList);
        }

        [HttpPost]
        public async Task<ActionResult> Search(string CityName)
        {
            if (CityName != null)  
            {
                TempData["CityName"] = CityName;
                return Redirect("/Weather/Details");
            }
            else
            {
                return await Search();
            }
       
        }

       [HttpGet]
        public async Task<ActionResult> Details()
        {
            try
            {
                var showWeather = new WeatherData();
                showWeather.name = TempData["CityName"].ToString();
                TempData.Remove("CityName");
                showWeather = await Seed.PopulateWeatherModel(showWeather.name);

                if (!showWeather.Equals(null))
                {
                    return View(showWeather);
                }
                else
                {
                    return NotFound();
                }
            }
            catch(NullReferenceException)
            {
                return NotFound();
            }
            catch(Exception)
            {
                return NotFound();
            }
        }
    }
}

WebWeatherApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebWeatherApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar-inverse bg-white border-bottom box-shadow">
            @*<div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Weather" asp-action="Search">Search By City</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>*@
        </nav>
    </header>
    <div class="mw-100">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-2" style="text-align:left;">
                    <div class="row">
                        <a href="https://github.com/Carpenteri1" class="d-block">
                            <img src="https://www.flaticon.com/svg/vstatic/svg/2111/2111432.svg?token=exp=1611438684~hmac=3c301b0744669fae0ed77d99a967a96a" height="20" width="20" />
                        </a>
                        @*
                            <a href="" class="d-block">
                                <img src="https://www.flaticon.com/svg/vstatic/svg/174/174857.svg?token=exp=1611438577~hmac=e164a78987da3a63f62f8fa7d4bbe5c0" height="20" width="20" />
                            </a>
                        *@
                    </div>
                    <div class="row">

                    </div>
                    <div class="row"></div>
                </div>
                <div class="col-8">

                </div>
                <div class="col-2"></div>
            </div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebWeatherApp/Views/Weather/Details.cshtml
@model WeatherApp.Data.WeatherData

@{
    string url ="http://openweathermap.org/img/wn/" + Model.weather[0].icon + "@2x.png";
}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div style="height:2.5vw;"></div>
            <div class="card shadow text-white" style="background-color: #292a2c !important;font-family:'Times New Roman'">
                <div class="card-body">
                    <h4 class="card-title">Weather in @Html.DisplayFor(model => model.name)</h4>
                    <div style="border-bottom:2px solid #968d7b;width:100%;"></div>
                    <div class="card-img">
                        <img src=@url />
                    </div>
                    <dl class="row">
                        <dt class="col-2">
                            General Info:
                        </dt>
                        <dd class="col-10">
                            @Html.DisplayFor(model => model.weather[0].main)
                        </dd>
                        <dt class="col-3" style="margin-right:-3vw;">
                            Temperature:
                        </dt>
                        <dd class="col-9">
                            @Html.DisplayFor(model => model.main.temp)°C
                        </dd>
                        <dt class="col-2">
                            Highest:
                        </dt>
                        <dd class="col-10">
                            @Html.DisplayFor(model => model.main.temp_max)°C
                        </dd>
                        <dt class="col-2">
                            Lowest:
                        </dt>
                        <dd class="col-10">
                            @Html.DisplayFor(model => model.main.temp_min)°C
                        </dd>
                        <dt class="col-3" style="margin-right:-3.vw;">
                            Feels like:
                        </dt>
                        <dd class="col-9" >
                            @Html.DisplayFor(model => model.main.feels_like)°C
                        </dd>
                        <dt class="col-2">
                            Humidity:
                        </dt>
                        <dd class="col-10">
                            @Html.DisplayFor(model => model.main.humidity)
                        </dd>
                        <dt class="col-2">
                            Pressure:
                        </dt>
                        <dd class="col-10">
                            @Html.DisplayFor(model => model.main.pressure) Bar
                        </dd>
                    </dl>
                    <a asp-area="" asp-controller="Weather" asp-action="Search" class="btn btn-primary text-white" style="margin-left:85%;font-family:'Times New Roman'">Cancel</a>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div> 
</div>

WebWeatherApp/Views/Weather/Search.cshtml
@model List<WeatherApp.Data.WeatherData>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div class="container-fluid jumbotron mw-100 img-fluid">
    <div class="row center mw-100 w-100">
        <div class="col-5"></div>
        <div class="col-2">
            <h1 style="font-family:'Times New Roman'">Hello world</h1>
        </div>
        <div class="col-5"></div>
    </div>
</div>
<div class="shadow text-left text-white" style="background-color:#3f3f3e;">
    <div class="row mw-100 center w-100">
        <div class="col-5"></div>
        <div class="col-2">
            <div style="height:0.5vw;"></div>
            @using (Html.BeginForm("Search", "Weather"))
            {

                <label class="d-block">Search By City Name</label>
                @Html.TextBox("CityName")
                <button class="d-inline-block btn btn-primary text-white p-2" type="submit" value="Search" style="margin-left:0.2vw;font-family:'Times New Roman'">Search</button>
            }
            <div style="height:0.5vw;"></div>
        </div>
        <div class="col-5"></div>
    </div>
</div>
<div style="height:16vw;"></div>
<div class="shadow text-white" style="background-color:#3f3f3e;">
    <div class="row mw-100 center w-100">
        <div class="col-3"></div>
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-3 text-dark">
            <div id="piechart">
                @if (Model == null ||
                  Model.Count <= 0)
                {
                    <div class="card">
                        <div class="card-body">
                            <div class="card-title">
                                <h4 style="color:red;text-align:center;">Error! Could not read data</h4>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card">
                        <div class="card-body">
                            <div class="card-title">Population data</div>
                            <div class="card-text">
                                <script type="text/javascript">
                    // Load google charts
                    google.charts.load('current', { 'packages': ['corechart'] });
                    google.charts.setOnLoadCallback(drawChart);

                    // Draw the chart and set the chart values. TODO needs to grab value from Model[e].city.population
                    function drawChart() {
                        var data = google.visualization.arrayToDataTable([
                            ['Task', 'Population'],
                            ['@Model[0].name', 1000],
                            ['@Model[1].name', 2060],
                            ['@Model[2].name', 4004],
                            ['@Model[3].name', 3060],
                            ['@Model[4].name', 2000]
                        ]);

                        // Optional; add a title and set the width and height of the chart
                        var options = {'width': 800, 'height': 400 };

                        // Display the chart inside the <div> element with id="piechart"
                        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
                        chart.draw(data, options);
                    }
                                </script>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</div>
<div style="height:16vw;"></div>